services:
    redis:
        image: redis/redis-stack
        ports:
          - "16379:6379"
        volumes:
          - $PWD/data:/data
    hasher:
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - 5001:5001